version: '3'

services:
  hospqa-etl:
    build:
      context: ./etl
    env_file:
      - .env

  api:
    build:
      context: ./api
    env_file:
      - .env
    depends_on:
      - hospqa-etl
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
    env_file:
      - .env
    depends_on:
      - api
    ports:
      - "8501:8501"